core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import activate_user_account, signup, CustomLoginView, PasswordReset

# from users.views import validate_username

app_name = 'users'

urlpatterns = [
    re_path(r'activate/(?P<signed_user>[0-9A-Za-z_\-]+/[A-Za-z0-9_=-]+/[A-Za-z0-9_=-]+)/$',
            activate_user_account, name='activate_user_account'),
    path('signup/', signup, name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html',
                                                                   success_url=reverse_lazy('users:password_change_done')),
         name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_changed.html'), name='password_change_done'),
    path('password_reset/', PasswordReset.as_view(success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/email_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_confirm.html',
                                                                                success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_confirmed.html'), name='password_reset_complete'),
  

]

user/models.py
import email
import uuid
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.db import models
from .managers import CustomUserManager


class CustomUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = None
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    email_confirmed = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

user/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import UsernameField, UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _


class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label=False,
        widget=forms.PasswordInput(attrs={'placeholder': _('Enter password'), 'autocomplete': 'new-password'}),
        strip=False,
        min_length=8,
        help_text=_("Password must be at least 8 characters long."),
        max_length=18,
        required=True,
    )

    password2 = forms.CharField(
        label=False,
        widget=forms.PasswordInput(attrs={'placeholder': _('Confirm password'), 'autocomplete': 'new-password'}),
        strip=False,
        min_length=8,
        help_text=_("Password must be at least 8 characters long."),
        max_length=18,
        required=True,
    )

    use_required_attribute = False

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email',)



class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email',)



class CustomAuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    username = UsernameField(
        required=False,
        widget=forms.TextInput(attrs={'autofocus': True,}),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
        required=False,
    )


    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }


    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the max length and label for the "username" field.
        self.username_field = get_user_model()._meta.get_field(get_user_model().USERNAME_FIELD)
        self.fields['username'].max_length = self.username_field.max_length or 254
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)


    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )


    def get_user(self):
        return self.user_cache



    def get_invalid_login_error(self):
        return forms.ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'username': self.username_field.verbose_name},
        )

user/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model, login as auth_login
from django.contrib.auth.views import LoginView, PasswordResetView
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views.generic import CreateView
from django.urls import reverse
from django.utils.translation import get_language, gettext_lazy as _
from .user_crypt import decoder
from .tasks import mail_send
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomAuthenticationForm

User = get_user_model()

class PasswordReset(PasswordResetView):
    def form_valid(self, form):
        email = form.cleaned_data['email']
        if not User.objects.filter(email__iexact=email).exists():
            messages.error(self.request, _(f"No user with email {email} exists."))
            return render(self.request, 'registration/password_reset_form.html')


        self.extra_email_context = {
            'fullurlstatic': self.request.build_absolute_uri('/static/'),
            'host': self.request.get_host(),
            'protocol': self.request.scheme,
        }
        self.html_email_template_name = 'email/password_reset_email.html'
        self.email_template_name = 'email/password_reset_email.txt'

        return super().form_valid(form)


def activate_user_account(request, signed_user=None):
    user, signature = decoder(request, signed_user)
    if user and signature:
        user.email_confirmed = True
        user.save()
        return render(request, 'email_verify_done.html', {'user': user})

    elif user:
        host = request.get_host()
        scheme = request.scheme
        lang = get_language()
        mail_send.delay(lang, scheme, host, user.pk)
        return render(request, 'email_verify_end_of_time.html')

    else:
        return render(request, 'user_does_not_exist.html')


def signup(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password1'])
            new_user.save()
            mail_send.delay(get_language(), request.scheme, request.get_host(), new_user.pk)
            return render(request, 'registration/signup_done.html', {'new_user': new_user})

    else:
        user_form = CustomUserCreationForm()
    return render(request, 'registration/signup.html', {'user_form': user_form})



class CustomLoginView(LoginView):
    form_class = CustomAuthenticationForm

    def form_valid(self, form):
        auth_login(self.request, form.get_user(), backend='users.authentication.CustomModelBackend')
        return HttpResponseRedirect(self.get_success_url())


    def form_invalid(self, form):
        num_attempt = self.request.session.get('num_attempt', 0)
        if num_attempt < 2:
            self.request.session['num_attempt'] = num_attempt + 1
        
        else:
            self.request.session['num_attempt'] = 2


        context = self.get_context_data(form=form)
        context['num_attempt'] = num_attempt

        # if num_attempt == 1:
        #     post_url = self.request.scheme + '://' + self.request.get_host() + reverse('v2:reset_password_reset')
        #     post_data = {'email': self.request.POST['username']}
        #     reset_pass_email(post_url, post_data)

        return self.render_to_response(context=context)

user/templates/_base.html
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
<div class="container">
    {% block content %}
    {% endblock %}

    {% block javascripts %}
    {% endblock %}

</body>
</html>

user/templates/email_verify_done.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>SyTech - {% trans 'Email address confirmed' %}</title>
{% endblock head %}

{% block content %}
<section class="main email-verify-done container-fluid d-flex align-items-center">
    <div class="container transparent justify-content-center py-6 py-md-0 mx-auto px-lg-5">
        {% if user.is_active %}
            {% if reuqest.user.is_authenticated %}
            <a class="text-center" href="#">Active</a>

            {% else %}
            <h3 class="text-center py-1 my-3">
                {% trans 'Your email address confirmed!' %}
                <br>
                {% trans 'You can' %}
                <a href="{% url 'users:login' %}" class="text-primary"> {% trans 'log in now' %}</a>
                {% trans 'or do it in your mobile app' %}
            </h3>
            {% endif %}
        {% else %}
        <p class="text-center">{% trans "Something went wrong." %}</p>
        {% endif %}
    </div>
</section>

<script>
setTimeout(() => {
    window.location.href = "{% url 'users:login' %}"
}, 10000)
</script>
{% endblock content %}

user/templates/email_verify_end_of_time.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>SyTech - {% trans 'Verify your email' %}</title>
{% endblock head %}

{% block content %}
<section class="main email-verify-done container-fluid d-flex align-items-center">
    <div class="container justify-content-center py-4 py-md-0 mt-4">
        <h1 class="text-center">{% trans 'Confirm your email address.' %}</h1>
        <p>{% blocktrans %}This e-mail confirmation link expired or is invalid. We have sent you an email with a new link. Please check your mail.{% endblocktrans %}</p>
    </div>
</section>
{% endblock content %}

user/templates/preorder_done.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>SyTech - {% trans 'Welcome' %}</title>
{% endblock head %}

{% block content %}
<section class="main preorder-done container-fluid d-flex align-items-center">
    <div class="container justify-content-center py-4 py-md-0 mt-4">
        <p class="text-secondary pt-4 text-center">
        {% trans 'Your preorder is done' %}
        </p>
    </div>
</section>
{% endblock content %}

user/templates/user_does_not_exist.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>SyTech - {% trans 'User`s verification' %}</title>
{% endblock head %}

{% block content %}
<section class="main user_does_not_exist container-fluid d-flex align-items-center">
    <div class="container justify-content-center py-4 py-md-0 mt-4">
        <h1 class="text-center">{% trans "User does not exist" %}</h1>
        <p>
            {% blocktrans %}User does not exist. We checked our database and unfortunately did not find you in it.Please go through the {% endblocktrans %}
            <a href="{% url 'users:signup' %}">{% trans 'registration process' %}</a>.
            {% trans 'Or contact with our' %}
            <a href="mailto:support@intime.digital">
            {% trans 'customer service' %}
            </a>
        </p>
    </div>

{% endblock content %}